version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

parameters:
  artifact-name:
    type: string
    default: nitrogen

jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    environment:
      _JAVA_OPTIONS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - setup
      - persist_to_workspace:
          root: ~/project/build/libs
          paths: 
            - << pipeline.parameters.artifact-name >>-*.jar
  deploy:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    environment:
      _JAVA_OPTIONS: -Xmx3200m
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - setup
      - run: sleep 560
      - run: gradle publish

commands:
  setup:
    steps:
      - checkout
      - gradle/with_cache:
          steps: 
            - run: gradle build --build-cache
      - store_artifacts:
          path: ~/project/build/libs

workflows:
  build:
    jobs:
      - build
  deploy:
    jobs:
      - deploy:
          context:
            - maven
          filters:
            tags:
              only: 
                - /.*/
            branches:
              ignore: 
                - /.*/